import type { CardUpgrade } from './types';

// 每张卡独立配置；费用、卡面和结算共用这些最终强化值。
export const CARD_UPGRADES: Record<string, CardUpgrade> = {
 strike:{damage:10,text:'造成 10 点伤害。'},
 guard:{shield:10,text:'获得 10 护盾。'},
 haste:{draw:2,text:'抽 2 张牌。耗竭。'},
 fortify:{shield:20,text:'获得 20 护盾。'},
 mend:{heal:8,text:'回复 8 点生命。耗竭。'},
 battery:{energy:2,text:'获得 2 点行动力。耗竭。'},
 study:{draw:3,text:'抽 3 张牌。'},
 purge:{draw:2,text:'清除手牌中的故障牌，抽 2 张。耗竭。'},
 brace:{shield:8,text:'获得 8 护盾，抽 1 张牌。'},
 shieldbash:{damage:7,text:'造成 7 ＋当前护盾一半的伤害。'},
 charge:{shield:7,text:'获得 2 蓄能，获得 7 护盾。'},
 cannon:{damage:17,text:'造成 17 伤害，消耗全部蓄能，每层额外 4 伤害。'},
 fireball:{damage:9,text:'造成 9 伤害，施加 2 灼烧。'},
 rock:{damage:14,text:'造成 14 点伤害。'},
 ignite:{damage:6,text:'造成 6 伤害；消耗目标灼烧，每层额外 3 伤害。'},
 inferno:{damage:18,text:'对所有敌人造成 18 伤害。耗竭。'},
 doublecut:{damage:7,text:'造成 7×2 段伤害。'},
 roar:{cost:0,text:'本场攻击每段伤害＋2。耗竭。'},
 heatwave:{damage:6,text:'对所有敌人造成 6 伤害，施加 2 灼烧。'},
 sacrifice:{draw:2,text:'失去 3 生命，获得 1 行动力，抽 2 张牌。耗竭。'},
 flare:{shield:11,text:'获得 11 护盾，对所有敌人施加 1 灼烧。'},
 leaf:{damage:5,text:'造成 5×2 段伤害，施加 1 符印。'},
 illusion:{copyChoice:true,draw:1,text:'选择手中一张可复制牌；复制品耗竭。抽 1 张牌。每回合最多复制 2 次。'},
 talisman:{shield:7,text:'施加 3 符印，获得 7 护盾。'},
 seal:{damage:8,text:'造成 8 伤害；消耗符印，每层额外 5 伤害。'},
 spirit:{damage:10,text:'造成 10 伤害，施加 1 灼烧和 1 符印。'},
 barrier:{shield:13,text:'获得 13 护盾。'},
 insight:{draw:3,text:'抽 3 张牌。耗竭。'},
 cyclone:{damage:14,text:'对所有敌人造成 14 伤害，施加 1 符印。'},
 ritual:{cost:0,text:'本场攻击每段伤害＋1，抽 1 张牌。耗竭。'},
 royal:{damage:25,shield:11,text:'造成 25 伤害，获得 11 护盾。'},
 aegis:{shield:16,text:'获得 16 护盾，抽 1 张牌。'},
 megido:{damage:22,text:'失去 3 生命；对所有敌人造成 22 伤害、施加 4 灼烧。耗竭。'},
 apocalypse:{burn:7,text:'对所有敌人施加 7 灼烧。'},
 sacred:{shield:13,text:'获得 13 护盾，抽 2 张牌。耗竭。'},
 mirrors:{damage:11,text:'造成 11 伤害，消耗符印每层追加 5 伤害。'},
 foxguardian:{damage:13,shield:9,text:'造成 13 伤害，获得 9 护盾。'},
 mandala:{shield:22,text:'获得 22 护盾，对所有敌人施加 2 符印。'},
 darkflame:{damage:10,text:'造成 10 伤害，施加 3 灼烧。'},
 bloodedge:{damage:19,text:'失去 3 生命，造成 19 伤害。'},
 foxcurse:{damage:8,text:'造成 8 伤害，施加 2 符印和 1 虚弱。'},
 shadowseal:{shield:10,text:'获得 10 护盾，施加 2 符印。'},
 drain:{damage:11,text:'造成 11 伤害；若造成生命伤害，回复 3 生命。'},
 chaoslance:{damage:26,text:'失去 3 生命，造成 26 伤害；若造成生命伤害，回复 5 生命。'},
 chaosward:{shield:21,text:'失去 3 生命，获得 21 护盾，抽 1 张牌。'},
 tinyTwister:{damage:8,text:'对所有敌人造成 8 伤害。'},
 blazingShot:{damage:11,text:'造成 11 伤害；若有蓄能，额外造成 2 伤害，不消耗蓄能。'},
 gatling:{damage:4,text:'造成 4×3 段伤害。'},
 dumUpper:{damage:12,shield:7,text:'造成 12 伤害，获得 7 护盾。'},
 blackGatling:{damage:5,shield:6,text:'造成 5×2 段伤害，获得 6 护盾。'},
 ambushUpper:{damage:13,text:'造成 13 伤害，施加 2 虚弱。'},
 rapidFire:{damage:4,text:'造成 4×3 段伤害，抽 1 张牌。'},
 goldTriangle:{damage:16,text:'对所有敌人造成 16 伤害。'},
 blackReload:{shield:11,text:'获得 11 护盾，获得 2 蓄能。'},
 blackMissile:{damage:18,text:'造成 18 伤害，消耗全部蓄能，每层额外 4 伤害。'},
 giantMissile:{damage:9,text:'造成 9×3 段伤害。'},
 burstShot:{damage:5,text:'对所有敌人造成 5×2 段伤害。'},
 heavySalvo:{damage:15,text:'造成 15 伤害，消耗全部蓄能，每层额外 6 伤害。耗竭。'},
 fortressLoad:{shield:15,text:'获得 15 护盾，获得 2 蓄能。'},
 fault:{cost:0,text:'不能产生效果。支付 0 行动力清除，本场耗竭。'},
};
