import type { CardDef, EnemyDef, Partner, Branch } from './types';
const card = (
  id: string,
  name: string,
  cost: number,
  kind: CardDef['kind'],
  family: CardDef['family'],
  text: string,
  art: string,
  effects: Partial<CardDef> = {},
): CardDef => ({
  id,
  name,
  cost,
  kind,
  family,
  text,
  art,
  ...(family !== 'common' && family !== 'status' ? { unlockForm: art } : {}),
  ...effects,
});
export const CARDS: Record<string, CardDef> = Object.fromEntries(
  [
    card('strike', '攻击指令', 1, 'attack', 'common', '造成 7 点伤害。', 'guilmon', { damage: 7 }),
    card('guard', '防御插件', 1, 'skill', 'common', '获得 7 点护盾。', 'hagurumon', { shield: 7 }),
    card('haste', '高速插件', 0, 'skill', 'common', '抽 1 张牌。耗竭。', 'picodevimon', {
      draw: 1,
      exhaust: true,
      upgradeText: '抽 2 张牌。耗竭。',
    }),
    card('fortify', '防护屏障', 2, 'skill', 'common', '获得 17 点护盾。', 'andromon', {
      shield: 17,
    }),
    card('mend', '数据修复', 2, 'skill', 'common', '回复 5 点生命。耗竭。', 'mushmon', {
      heal: 5,
      exhaust: true,
      upgradeText: '回复 7 点生命。耗竭。',
    }),
    card('battery', '能量装填', 0, 'skill', 'common', '获得 1 点行动力。耗竭。', 'hagurumon', {
      energy: 1,
      exhaust: true,
      upgradeDraw: 1,
      upgradeText: '获得 1 点行动力，抽 1 张牌。耗竭。',
    }),
    card('study', '紧急分析', 1, 'skill', 'common', '抽 2 张牌。', 'renamon', { draw: 2 }),
    card(
      'purge',
      '净化程序',
      0,
      'skill',
      'common',
      '清除手牌中的故障牌，抽 1 张。耗竭。',
      'taomon',
      {
        special: 'purge',
        draw: 1,
        exhaust: true,
        upgradeText: '清除手牌中的故障牌，抽 2 张。耗竭。',
      },
    ),
    card('brace', '战术整备', 1, 'skill', 'common', '获得 5 护盾，抽 1 张牌。', 'leomon', {
      shield: 5,
      draw: 1,
    }),
    card('shieldbash', '盾击', 1, 'attack', 'common', '造成 4 ＋当前护盾一半的伤害。', 'dukemon', {
      damage: 4,
      special: 'shieldhit',
    }),
    card('charge', '蓄能指令', 1, 'power', 'common', '获得 1 蓄能，获得 4 护盾。', 'andromon', {
      charge: 1,
      shield: 4,
    }),
    card(
      'cannon',
      '脉冲炮',
      2,
      'attack',
      'common',
      '造成 14 伤害，消耗全部蓄能，每层额外 4 伤害。',
      'wargrowlmon',
      { damage: 14, special: 'cannon' },
    ),
    card('fireball', '火球', 1, 'attack', 'guilmon', '造成 6 伤害，施加 2 灼烧。', 'guilmon', {
      damage: 6,
      burn: 2,
    }),
    card('rock', '岩石粉碎', 1, 'attack', 'guilmon', '造成 11 点伤害。', 'guilmon', { damage: 11 }),
    card(
      'ignite',
      '烈焰引爆',
      1,
      'attack',
      'guilmon',
      '造成 3 伤害；消耗目标灼烧，每层额外 3 伤害。',
      'growlmon',
      { damage: 3, special: 'detonate' },
    ),
    card(
      'inferno',
      '原子爆焰',
      2,
      'attack',
      'guilmon',
      '对所有敌人造成 15 伤害。耗竭。',
      'wargrowlmon',
      { damage: 15, all: true, exhaust: true },
    ),
    card('doublecut', '双刃斩', 1, 'attack', 'guilmon', '造成 5×2 段伤害。', 'growlmon', {
      damage: 5,
      hits: 2,
    }),
    card('roar', '勇气咆哮', 1, 'power', 'guilmon', '本场攻击每段伤害＋1。耗竭。', 'guilmon', {
      strength: 1,
      exhaust: true,
      upgradeText: '本场攻击每段伤害＋2。耗竭。',
    }),
    card(
      'heatwave',
      '热浪',
      1,
      'attack',
      'guilmon',
      '对所有敌人造成 3 伤害，施加 1 灼烧。',
      'growlmon',
      { damage: 3, burn: 1, all: true },
    ),
    card(
      'sacrifice',
      '危险过载',
      0,
      'skill',
      'guilmon',
      '失去 3 生命，获得 1 行动力，抽 1 张牌。耗竭。',
      'guilmon',
      {
        special: 'sacrifice',
        energy: 1,
        draw: 1,
        exhaust: true,
        upgradeText: '失去 3 生命，获得 2 行动力，抽 2 张牌。耗竭。',
      },
    ),
    card(
      'flare',
      '余烬护甲',
      1,
      'skill',
      'guilmon',
      '获得 8 护盾，对所有敌人施加 1 灼烧。',
      'wargrowlmon',
      { shield: 8, burn: 1, all: true },
    ),
    card('leaf', '狐叶楔', 1, 'attack', 'renamon', '造成 3×2 段伤害，施加 1 符印。', 'renamon', {
      damage: 3,
      hits: 2,
      mark: 1,
    }),
    card(
      'illusion',
      '狐变虚',
      1,
      'skill',
      'renamon',
      '复制手中最左侧非复制、非故障牌；复制牌耗竭。',
      'renamon',
      { special: 'copy' },
    ),
    card('talisman', '符咒', 1, 'skill', 'renamon', '施加 3 符印，获得 4 护盾。', 'renamon', {
      mark: 3,
      shield: 4,
    }),
    card(
      'seal',
      '解印',
      1,
      'attack',
      'renamon',
      '造成 5 伤害；消耗符印，每层额外 5 伤害。',
      'renamon',
      { damage: 5, special: 'markburst' },
    ),
    card(
      'spirit',
      '狐火',
      1,
      'attack',
      'renamon',
      '造成 7 伤害，施加 1 灼烧和 1 符印。',
      'kyubimon',
      { damage: 7, burn: 1, mark: 1 },
    ),
    card('barrier', '金刚结界', 1, 'skill', 'renamon', '获得 10 护盾。', 'taomon', { shield: 10 }),
    card('insight', '灵视', 0, 'skill', 'renamon', '抽 2 张牌。耗竭。', 'renamon', {
      draw: 2,
      exhaust: true,
      upgradeText: '抽 3 张牌。耗竭。',
    }),
    card(
      'cyclone',
      '狐炎龙',
      2,
      'attack',
      'renamon',
      '对所有敌人造成 11 伤害，施加 1 符印。',
      'kyubimon',
      { damage: 11, mark: 1, all: true },
    ),
    card(
      'ritual',
      '阴阳术',
      1,
      'power',
      'renamon',
      '本场攻击每段伤害＋1，抽 1 张牌。耗竭。',
      'taomon',
      { strength: 1, draw: 1, exhaust: true },
    ),
    card('royal', '皇家枪击', 2, 'attack', 'duke', '造成 22 伤害，获得 8 护盾。', 'dukemon', {
      damage: 22,
      shield: 8,
    }),
    card('aegis', '圣盾守护', 1, 'skill', 'duke', '获得 10 护盾，抽 1 张牌。', 'dukemon', {
      shield: 10,
      draw: 1,
    }),
    card(
      'gramLance',
      '圣枪格拉墨',
      2,
      'attack',
      'duke',
      '造成 12 伤害；当前护盾每 3 点追加 1 伤害。',
      'dukemon',
      { damage: 12, special: 'shieldhit', shieldDiv: 3 },
    ),
    card(
      'megido',
      '灭世烈焰',
      2,
      'attack',
      'megidra',
      '失去 3 生命；对所有敌人造成 19 伤害、施加 4 灼烧。耗竭。',
      'megidramon',
      { damage: 19, burn: 4, all: true, special: 'sacrifice', exhaust: true },
    ),
    card(
      'apocalypse',
      '地狱咆哮',
      1,
      'attack',
      'megidra',
      '对所有敌人施加 3 灼烧。',
      'megidramon',
      { burn: 3, all: true },
    ),
    card(
      'judgment',
      '末日审判',
      2,
      'attack',
      'megidra',
      '对所有敌人造成 6 伤害；每个目标的灼烧每层追加 3 伤害，灼烧不消耗。',
      'megidramon',
      { damage: 6, all: true, special: 'pyre', burnPower: 3 },
    ),
    card(
      'sacred',
      '金刚界曼荼罗',
      1,
      'skill',
      'sakuya',
      '获得 10 护盾，抽 2 张牌。耗竭。',
      'sakuyamon',
      { shield: 10, draw: 2, exhaust: true },
    ),
    card(
      'mirrors',
      '净化之印',
      1,
      'attack',
      'sakuya',
      '造成 8 伤害，消耗符印每层追加 5 伤害。',
      'sakuyamon',
      { damage: 8, special: 'markburst' },
    ),
    card(
      'kaguraBell',
      '神乐铃',
      1,
      'skill',
      'sakuya',
      '施加 2 符印，抽 1 张牌；若本回合已消耗过符印，改为施加 4 符印。',
      'sakuyamon',
      {
        mark: 2,
        draw: 1,
        burstMarkBonus: 2,
        upgradeText: '施加 2 符印，抽 2 张牌；若本回合已消耗过符印，改为施加 4 符印。',
      },
    ),
    card(
      'foxguardian',
      '管狐术',
      1,
      'attack',
      'kuzuha',
      '造成 10 伤害，获得 6 护盾。',
      'kuzuhamon',
      { damage: 10, shield: 6 },
    ),
    card(
      'mandala',
      '胎藏界曼荼罗',
      2,
      'skill',
      'kuzuha',
      '获得 19 护盾，对所有敌人施加 2 符印。',
      'kuzuhamon',
      { shield: 19, mark: 2, all: true },
    ),
    card(
      'izuna',
      '式神·饭纲',
      1,
      'skill',
      'kuzuha',
      '抽 1 张牌；若本回合式神已苏醒（第二张技能牌起），再抽 1 张。',
      'kuzuhamon',
      { draw: 1, special: 'izuna' },
    ),
    card(
      'darkflame',
      '暗炎弹',
      1,
      'attack',
      'guilmon',
      '造成 7 伤害，施加 2 灼烧。',
      'blackgrowmon',
      { damage: 7, burn: 2, series: 'fireball' },
    ),
    card(
      'bloodedge',
      '血色利刃',
      1,
      'attack',
      'guilmon',
      '失去 3 生命，造成 13 伤害。',
      'blackgrowmon',
      { damage: 13, special: 'sacrifice' },
    ),
    card(
      'foxcurse',
      '焰玉咒',
      1,
      'attack',
      'renamon',
      '造成 5 伤害，施加 2 符印和 1 虚弱。',
      'youkomon',
      { damage: 5, mark: 2, weak: 1, series: 'leaf' },
    ),
    card(
      'runeShard',
      '碎符',
      0,
      'attack',
      'renamon',
      '造成 3 伤害；消耗符印，每层额外 4 伤害。',
      'youkomon',
      { damage: 3, special: 'markburst', markPower: 4 },
    ),
    card('shadowseal', '咒符结界', 1, 'skill', 'renamon', '获得 7 护盾，施加 2 符印。', 'doumon', {
      shield: 7,
      mark: 2,
      series: 'talisman',
    }),
    card(
      'sealBurst',
      '封灭阵',
      2,
      'attack',
      'renamon',
      '对所有敌人造成 6 伤害；消耗各自符印，每层额外 5 伤害。',
      'doumon',
      { damage: 6, all: true, special: 'markburst' },
    ),
    card(
      'drain',
      '生命汲取',
      1,
      'attack',
      'common',
      '造成 6 伤害；若造成生命伤害，回复 2 生命。',
      'chaosdukemon',
      { damage: 6, drain: 2 },
    ),
    card(
      'chaoslance',
      '混沌枪击',
      2,
      'attack',
      'chaos',
      '失去 3 生命，造成 23 伤害；若造成生命伤害，回复 5 生命。',
      'chaosdukemon',
      { damage: 23, special: 'sacrifice', drain: 5 },
    ),
    card(
      'chaosward',
      '暗黑圣盾',
      1,
      'skill',
      'chaos',
      '失去 3 生命，获得 18 护盾，抽 1 张牌。',
      'chaosdukemon',
      { shield: 18, draw: 1, special: 'sacrifice' },
    ),
    card(
      'abyssLance',
      '深渊龙枪',
      2,
      'attack',
      'chaos',
      '失去 3 生命，造成 14 伤害；若本回合已自损过，额外＋8 伤害。耗竭。',
      'chaosdukemon',
      {
        damage: 14,
        special: 'sacrifice',
        selfCostBonus: 8,
        exhaust: true,
        upgradeText: '失去 3 生命，造成 17 伤害；若本回合已自损过，额外＋8 伤害。耗竭。',
      },
    ),
    card(
      'tinyTwister',
      '小型龙卷风',
      1,
      'attack',
      'terriermon',
      '对所有敌人造成 4 伤害。',
      'terriermon',
      { damage: 4, all: true },
    ),
    card(
      'blazingShot',
      '炽热气弹',
      1,
      'attack',
      'terriermon',
      '造成 8 伤害；若有蓄能，额外造成 2 伤害，不消耗蓄能。',
      'terriermon',
      { damage: 8, chargedDamage: 2 },
    ),
    card('gatling', '加特林机枪', 1, 'attack', 'terriermon', '造成 3×3 段伤害。', 'galgomon', {
      damage: 3,
      hits: 3,
      upgradeDamage: 1,
    }),
    card(
      'dumUpper',
      '达姆达姆勾拳',
      1,
      'attack',
      'terriermon',
      '造成 9 伤害，获得 4 护盾。',
      'galgomon',
      { damage: 9, shield: 4 },
    ),
    card(
      'blackGatling',
      '黑加特林机枪',
      1,
      'attack',
      'terriermon',
      '造成 4×2 段伤害，获得 3 护盾。',
      'blackgalgomon',
      { damage: 4, hits: 2, shield: 3, upgradeDamage: 1 },
    ),
    card(
      'ambushUpper',
      '伏击勾拳',
      1,
      'attack',
      'terriermon',
      '造成 10 伤害，施加 2 虚弱。',
      'blackgalgomon',
      { damage: 10, weak: 2 },
    ),
    card(
      'rapidFire',
      '疾速射击',
      1,
      'attack',
      'terriermon',
      '造成 3×3 段伤害，抽 1 张牌。',
      'rapidmon',
      { damage: 3, hits: 3, draw: 1, upgradeDamage: 1 },
    ),
    card(
      'goldTriangle',
      '黄金三角',
      2,
      'attack',
      'terriermon',
      '对所有敌人造成 13 伤害。',
      'rapidmon',
      { damage: 13, all: true },
    ),
    card(
      'blackReload',
      '战术·装甲装填',
      1,
      'skill',
      'terriermon',
      '获得 8 护盾，获得 2 蓄能。',
      'blackrapidmon',
      { shield: 8, charge: 2 },
    ),
    card(
      'blackMissile',
      '战术·定点轰击',
      2,
      'attack',
      'terriermon',
      '造成 15 伤害，消耗全部蓄能，每层额外 4 伤害。',
      'blackrapidmon',
      { damage: 15, special: 'cannon' },
    ),
    card('giantMissile', '巨型导弹', 2, 'attack', 'saint', '造成 8×3 段伤害。', 'saintgalgomon', {
      damage: 8,
      hits: 3,
      upgradeDamage: 1,
    }),
    card(
      'burstShot',
      '爆裂射击',
      1,
      'attack',
      'saint',
      '对所有敌人造成 4×2 段伤害。',
      'saintgalgomon',
      { damage: 4, hits: 2, all: true, upgradeDamage: 1 },
    ),
    card(
      'fullSalvo',
      '全力齐射',
      1,
      'attack',
      'saint',
      '造成 6 伤害，消耗全部蓄能，每层额外 3 伤害。',
      'saintgalgomon',
      { damage: 6, special: 'cannon', chargeMultiplier: 3 },
    ),
    card(
      'heavySalvo',
      '战术·重装齐射',
      2,
      'attack',
      'blacksaint',
      '造成 12 伤害，消耗全部蓄能，每层额外 5 伤害。耗竭。',
      'blacksaintgalgomon',
      { damage: 12, special: 'cannon', chargeMultiplier: 5, exhaust: true },
    ),
    card(
      'fortressLoad',
      '战术·要塞整备',
      1,
      'skill',
      'blacksaint',
      '获得 10 护盾，获得 2 蓄能。',
      'blacksaintgalgomon',
      { shield: 10, charge: 2 },
    ),
    card(
      'suppressBarrage',
      '压制弹幕',
      1,
      'attack',
      'terriermon',
      '对所有敌人造成 5 伤害，施加 1 虚弱。',
      'blackgalgomon',
      { damage: 5, all: true, weak: 1 },
    ),
    card(
      'gravityField',
      '重力力场',
      2,
      'skill',
      'terriermon',
      '获得 7 护盾，对所有敌人施加 2 虚弱。',
      'blackrapidmon',
      { shield: 7, weak: 2, all: true },
    ),
    card(
      'zoneSuppress',
      '战术·全域压制',
      2,
      'attack',
      'blacksaint',
      '对所有敌人造成 8 伤害、施加 1 虚弱，消耗全部蓄能，每层额外 3 伤害。',
      'blacksaintgalgomon',
      { damage: 8, all: true, weak: 1, special: 'cannon', chargeMultiplier: 3 },
    ),
    card(
      'fault',
      '数据故障',
      1,
      'status',
      'status',
      '不能产生效果。支付 1 行动力清除，本场耗竭。',
      'core',
      { exhaust: true },
    ),
    card(
      'nightfire',
      '暗夜之火',
      1,
      'attack',
      'impmon',
      '造成 5 点伤害；此牌每造成 5 点伤害，获得 1 噬能。',
      'impmon',
      {
        damage: 5,
        convert: 5,
      },
    ),
    card('taunt', '嘲笑', 1, 'skill', 'impmon', '施加 2 虚弱，抽 1 张牌。', 'impmon', { weak: 2, draw: 1 }),
    card('prank', '恶作剧', 0, 'skill', 'impmon', '获得 1 层噬能。耗竭。', 'impmon', {
      devour: 1,
      exhaust: true,
      upgradeText: '获得 2 层噬能。耗竭。',
    }),
    card(
      'devourTrick',
      '噬能戏法',
      1,
      'attack',
      'impmon',
      '造成 6 伤害；消耗至多 3 层噬能，每层额外 3 伤害。',
      'impmon',
      { damage: 6, special: 'devour', devourPower: 3 },
    ),
    card(
      'frostSorcery',
      '冰晶魔法',
      1,
      'attack',
      'impmon',
      '造成 7 伤害，施加 1 虚弱。',
      'sorcerymon',
      { damage: 7, weak: 1 },
    ),
    card(
      'magicShield',
      '魔术屏障',
      1,
      'skill',
      'impmon',
      '获得 6 护盾；消耗至多 3 层噬能，每层额外 2 护盾。',
      'sorcerymon',
      { shield: 6, devourShield: 2 },
    ),
    card(
      'devourAura',
      '噬能光环',
      1,
      'power',
      'impmon',
      '本场战斗噬能上限＋2，获得 2 噬能。耗竭。',
      'sorcerymon',
      {
        special: 'devouraura',
        exhaust: true,
        upgradeText: '本场战斗噬能上限＋2，获得 3 噬能。耗竭。',
      },
    ),
    card(
      'soulHarvest',
      '灵魂收割',
      2,
      'attack',
      'impmon',
      '造成 10 点伤害，获得 1 噬能；随后消耗至多 3 层噬能，每层额外 3 伤害。',
      'matadormon',
      { damage: 10, special: 'devour', devourPower: 3, devour: 1 },
    ),
    card(
      'lureDance',
      '引逗剑舞',
      1,
      'attack',
      'impmon',
      '造成 7 伤害；若目标处于虚弱，额外造成 4 伤害。',
      'matadormon',
      { damage: 7, special: 'lure' },
    ),
    card('thousandCuts', '千羽剑雨', 2, 'attack', 'impmon', '造成 4×4 段伤害。', 'matadormon', {
      damage: 4,
      hits: 4,
      upgradeDamage: 1,
    }),
    card(
      'grandFinale',
      '华丽终幕',
      1,
      'skill',
      'impmon',
      '获得 6 护盾，获得 1 噬能。',
      'matadormon',
      { shield: 6, devour: 1 },
    ),
    card(
      'bloodClaw',
      '吸血魔爪',
      1,
      'attack',
      'impmon',
      '造成 8 伤害；每造成 4 点生命伤害，回复 1 生命。',
      'devimon',
      {
        damage: 8,
        drainRatio: 4,
        upgradeDamage: 2,
        upgradeDrainRatio: 3,
        upgradeText: '造成 10 伤害；每造成 3 点生命伤害，回复 1 生命。',
      },
    ),
    card(
      'nightmareWave',
      '恶梦冲击波',
      1,
      'skill',
      'impmon',
      '消耗全部噬能，每 3 层获得 1 力量。耗竭。',
      'devimon',
      {
        devourStrength: 3,
        exhaust: true,
        upgradeDraw: 1,
        upgradeText: '消耗全部噬能，每 3 层获得 1 力量，抽 1 张牌。耗竭。',
      },
    ),
    card(
      'devourCorrode',
      '噬能侵蚀',
      1,
      'skill',
      'impmon',
      '消耗 3 层噬能，施加 3 易伤；噬能不足 3 层时不消耗，施加 1 易伤。',
      'devimon',
      {
        devourVuln: 3,
        upgradeText: '消耗 3 层噬能，施加 4 易伤；噬能不足 3 层时不消耗，施加 2 易伤。',
      },
    ),
    card(
      'batSwarm',
      '蝙蝠群袭',
      1,
      'attack',
      'impmon',
      '造成 3×3 段伤害；此牌每造成 5 点伤害，获得 1 噬能。',
      'vamdemon',
      {
        damage: 3,
        hits: 3,
        convert: 5,
      },
    ),
    card(
      'crimsonRain',
      '深红血雨',
      2,
      'attack',
      'impmon',
      '对所有敌人造成 6 伤害，施加 1 虚弱；消耗至多 3 层噬能，每层额外 2 伤害。',
      'vamdemon',
      { damage: 6, weak: 1, all: true, special: 'devour', devourPower: 2 },
    ),
    card(
      'devourFeast',
      '噬能饱食',
      1,
      'skill',
      'impmon',
      '消耗至多 3 层噬能，每层回复 3 生命。',
      'vamdemon',
      { devourHeal: 3 },
    ),
    card(
      'bloodPact',
      '血之契约',
      1,
      'skill',
      'impmon',
      '失去 3 生命，获得 3 噬能，抽 1 张牌。',
      'vamdemon',
      {
        special: 'sacrifice',
        devour: 3,
        draw: 1,
        upgradeText: '失去 3 生命，获得 3 噬能，抽 2 张牌。',
      },
    ),
    card(
      'flamencoSlash',
      '弗拉明戈斩',
      2,
      'attack',
      'impmon',
      '造成 5×3 段伤害；每造成 4 点生命伤害，回复 1 生命。',
      'matadormonAwakened',
      { damage: 5, hits: 3, drainRatio: 4 },
    ),
    card(
      'curtainSpin',
      '谢幕回旋',
      1,
      'skill',
      'impmon',
      '抽 1 张牌；若本回合已打出攻击牌，行动力＋1。',
      'matadormonAwakened',
      {
        draw: 1,
        special: 'spinstep',
        upgradeText: '抽 2 张牌；若本回合已打出攻击牌，行动力＋1。',
      },
    ),
    card(
      'fatalPierce',
      '致命穿刺',
      1,
      'attack',
      'impmon',
      '造成 6 伤害；若是本回合第二张及以后的攻击牌，伤害翻倍。',
      'matadormonAwakened',
      { damage: 6, multiAttackDouble: true, upgradeDamage: 2, upgradeText: '造成 8 伤害；若是本回合第二张及以后的攻击牌，伤害翻倍。' },
    ),
    card(
      'twinClaw',
      '双重爪击',
      1,
      'attack',
      'impmon',
      '造成 4×2 段伤害；此牌每造成 4 点伤害，获得 1 噬能。',
      'beelzebumon',
      { damage: 4, hits: 2, convert: 4 },
    ),
    card(
      'deathCannon',
      '死亡加农炮',
      2,
      'attack',
      'impmon',
      '造成 12 伤害，消耗全部噬能（至多 6 层），每层额外 4 伤害。耗竭。',
      'beelzebumon',
      { damage: 12, special: 'devour', devourPower: 4, devourAll: true, exhaust: true },
    ),
    card(
      'gluttonyFeast',
      '暴食掠宴',
      1,
      'attack',
      'impmon',
      '造成 7 伤害；若此牌击败敌人，获得 2 噬能并抽 1 张牌。',
      'beelzebumon',
      {
        damage: 7,
        killDevour: 2,
        killDraw: 1,
        upgradeText: '造成 10 伤害；若此牌击败敌人，获得 2 噬能并抽 1 张牌。',
      },
    ),
    card(
      'gustCannon',
      '疾风加农',
      1,
      'attack',
      'impmon',
      '对所有敌人造成 4×2 段伤害；消耗至多 3 层噬能，每层增加 1 段。',
      'beelzebumonblaster',
      { damage: 4, hits: 2, all: true, devourHits: 1, upgradeDamage: 1 },
    ),
    card(
      'shiningWing',
      '光辉之翼',
      1,
      'skill',
      'impmon',
      '获得 10 护盾，抽 1 张牌。',
      'beelzebumonblaster',
      { shield: 10, draw: 1 },
    ),
    card(
      'windPressure',
      '风压推进',
      1,
      'skill',
      'impmon',
      '本回合下一张攻击牌段数＋1；若该牌至少 4 段，抽 1 张牌。',
      'beelzebumonblaster',
      {
        special: 'windup',
        windupHits: 1,
        upgradeText: '本回合下一张攻击牌段数＋2；若该牌至少 4 段，抽 1 张牌。',
      },
    ),
    card(
      'venomFog',
      '剧毒迷雾',
      2,
      'skill',
      'impmon',
      '对所有敌人施加 2 虚弱，获得 6 护盾；消耗至多 3 层噬能，每层额外施加 1 虚弱。',
      'venommyotismon',
      { weak: 2, shield: 6, all: true, devourWeak: 1 },
    ),
    card(
      'bloodFeast',
      '血腥宴席',
      2,
      'attack',
      'impmon',
      '造成 14 伤害；若造成生命伤害，回复 5 生命。耗竭。',
      'venommyotismon',
      { damage: 14, drain: 5, exhaust: true },
    ),
    card(
      'venomEmbrace',
      '腐毒之拥',
      1,
      'skill',
      'impmon',
      '施加 2 虚弱；消耗至多 3 层噬能，每层回复 2 生命。',
      'venommyotismon',
      {
        weak: 2,
        devourHeal: 2,
        upgradeText: '施加 2 虚弱；消耗至多 3 层噬能，每层回复 3 生命。',
      },
    ),
    card(
      'despairHowl',
      '绝望嚎叫',
      1,
      'skill',
      'impmon',
      '对所有敌人施加 1 虚弱，获得 2 噬能。',
      'belialvamdemon',
      { weak: 1, all: true, devour: 2 },
    ),
    card(
      'darkDisaster',
      '暗黑大灾害',
      2,
      'attack',
      'impmon',
      '失去 3 生命，造成 9×2 段伤害。',
      'belialvamdemon',
      { damage: 9, hits: 2, special: 'sacrifice' },
    ),
    card(
      'despairReap',
      '绝望收束',
      2,
      'attack',
      'impmon',
      '造成 5×2 段伤害；消耗至多 2 层噬能，每层增加 1 段；目标生命低于一半时每段额外 2 伤害。',
      'belialvamdemon',
      {
        damage: 5,
        hits: 2,
        devourHits: 1,
        devourHitsCap: 2,
        executeBonus: 2,
        upgradeDamage: 1,
        upgradeText:
          '造成 6×2 段伤害；消耗至多 2 层噬能，每层增加 1 段；目标生命低于一半时每段额外 2 伤害。',
      },
    ),
  ].map((c) => [c.id, c]),
);
export const PARTNERS: Record<
  Partner,
  { name: string; tag: string; description: string; forms: string[]; branches: Branch[] }
> = {
  guilmon: {
    name: '基尔兽',
    tag: '火焰 · 勇气',
    description: '用烈焰突破防线，或以圣盾守护羁绊。',
    forms: ['guilmon', 'growlmon', 'wargrowlmon'],
    branches: ['duke', 'megidra', 'chaos'],
  },
  renamon: {
    name: '妖狐兽',
    tag: '符印 · 灵巧',
    description: '编织符印与术式，让每一次出牌彼此呼应。',
    forms: ['renamon', 'kyubimon', 'taomon'],
    branches: ['sakuya', 'kuzuha'],
  },
  terriermon: {
    name: '大耳兽',
    tag: '连射 · 蓄能',
    description: '用连射掌握节奏，或蓄能化身重装炮台。',
    forms: ['terriermon', 'galgomon', 'rapidmon'],
    branches: ['saint', 'blacksaint'],
  },
  impmon: {
    name: '小妖兽',
    tag: '恶作剧 · 吞噬',
    description: '积攒噬能，在暴食与堕天之间选择你的魔王之路。',
    forms: ['impmon', 'sorcerymon', 'matadormon'],
    branches: ['gluttony', 'blast', 'venom', 'belial'],
  },
};
export const BRANCHES: Record<
  Branch,
  { name: string; art: string; tag: string; passive: string; cards: string[]; partner: Partner }
> = {
  saint: {
    name: '撒多格杜兽',
    art: 'saintgalgomon',
    tag: '连射压制',
    passive: '每回合第二张攻击牌结算后，获得 1 蓄能并抽 1 张牌。',
    cards: ['giantMissile', 'burstShot'],
    partner: 'terriermon',
  },
  blacksaint: {
    name: '黑撒多格杜兽',
    art: 'blacksaintgalgomon',
    tag: '重装炮击',
    passive: '每回合首次防御出牌额外获得 1 蓄能；首次成功消耗蓄能后，获得 6 护盾。',
    cards: ['heavySalvo', 'fortressLoad'],
    partner: 'terriermon',
  },
  chaos: {
    name: '混沌红莲骑士兽',
    art: 'chaosdukemon',
    tag: '血契循环',
    passive: '每回合首次主动自损后获得 6 护盾。',
    cards: ['chaoslance', 'chaosward'],
    partner: 'guilmon',
  },
  duke: {
    name: '红莲骑士兽',
    art: 'dukemon',
    tag: '圣盾反击',
    passive: '每回合首张防御技能额外获得 3 护盾。',
    cards: ['royal', 'aegis'],
    partner: 'guilmon',
  },
  megidra: {
    name: '灭世魔龙兽',
    art: 'megidramon',
    tag: '灼烧爆发',
    passive: '每回合首次施加灼烧，额外增加 2 层。',
    cards: ['megido', 'apocalypse'],
    partner: 'guilmon',
  },
  sakuya: {
    name: '沙古牙兽',
    art: 'sakuyamon',
    tag: '术式循环',
    passive: '每回合首次消耗符印，抽 1 张牌。',
    cards: ['sacred', 'mirrors'],
    partner: 'renamon',
  },
  kuzuha: {
    name: '葛叶兽',
    art: 'kuzuhamon',
    tag: '结界式神',
    passive: '每回合第二张技能牌触发式神，攻击一名敌人造成 4 伤害。',
    cards: ['foxguardian', 'mandala'],
    partner: 'renamon',
  },
  gluttony: {
    name: '别西卜兽',
    art: 'beelzebumon',
    tag: '暴食吞噬',
    passive: '每击败一个敌人，本场攻击每段伤害＋1，并回复 4 生命。',
    cards: ['twinClaw', 'deathCannon'],
    partner: 'impmon',
  },
  blast: {
    name: '别西卜兽 · 疾风形态',
    art: 'beelzebumonblaster',
    tag: '疾风连射',
    passive: '攻击牌的第 3 段及以后，每段伤害＋1。',
    cards: ['gustCannon', 'shiningWing'],
    partner: 'impmon',
  },
  venom: {
    name: '怨毒吸血魔兽',
    art: 'venommyotismon',
    tag: '剧毒吸血',
    passive: '施加虚弱额外＋1；每回合首次施加虚弱时回复 3 生命。',
    cards: ['venomFog', 'bloodFeast'],
    partner: 'impmon',
  },
  belial: {
    name: '贝利亚吸血魔兽',
    art: 'belialvamdemon',
    tag: '绝望收割',
    passive: '击败敌人时抽 1 张牌；消耗噬能时每层额外＋2 伤害。',
    cards: ['despairHowl', 'darkDisaster'],
    partner: 'impmon',
  },
};
export const FORM_NAMES: Record<string, string> = {
  terriermon: '大耳兽',
  galgomon: '加鲁哥兽',
  blackgalgomon: '黑加鲁哥兽',
  rapidmon: '拉比兽',
  blackrapidmon: '黑拉比兽',
  saintgalgomon: '撒多格杜兽',
  blacksaintgalgomon: '黑撒多格杜兽',
  blackgrowmon: '黑古拉兽',
  blackwargrowlmon: '黑大古拉兽',
  chaosdukemon: '混沌红莲骑士兽',
  youkomon: '妖狐兽（蓝）',
  doumon: '道士兽',
  guilmon: '基尔兽',
  growlmon: '古拉兽',
  wargrowlmon: '大古拉兽',
  renamon: '妖狐兽',
  kyubimon: '九尾狐兽',
  taomon: '祭师兽',
  dukemon: '红莲骑士兽',
  megidramon: '灭世魔龙兽',
  sakuyamon: '沙古牙兽',
  kuzuhamon: '葛叶兽',
  impmon: '小妖兽',
  sorcerymon: '术士兽',
  matadormon: '斗牛士兽',
  matadormonAwakened: '斗牛士兽 · 觉醒',
  devimon: '恶魔兽',
  vamdemon: '吸血魔兽',
  beelzebumon: '别西卜兽',
  beelzebumonblaster: '别西卜兽 · 疾风形态',
  venommyotismon: '怨毒吸血魔兽',
  belialvamdemon: '贝利亚吸血魔兽',
};
const enemy = (
  id: string,
  name: string,
  hp: number,
  style: EnemyDef['style'],
  support?: string,
): EnemyDef => ({ id, name, hp, style, art: id, scan: true, support });
export const ENEMIES: Record<string, EnemyDef> = Object.fromEntries(
  [
    enemy('gotsumon', '矿石兽', 30, 'expanded', '矿石核心：获得 2 蓄能。'),
    enemy('betamon', '比多兽', 26, 'expanded', '数据汲取：抽 2 张牌。'),
    enemy('monodramon', '独角龙兽', 32, 'expanded'),
    enemy('clockmon', '时钟兽', 34, 'expanded'),
    enemy('seadramon', '海龙兽', 46, 'expanded'),
    enemy('gekomon', '怪蛙兽', 30, 'expanded'),
    enemy('devimon', '恶魔兽', 68, 'expanded'),
    enemy('skullgreymon', '丧尸暴龙兽', 82, 'expanded'),
    enemy('machinedramon', '无限龙兽', 148, 'expanded'),
    enemy('goblimon', '哥布林兽', 29, 'charge'),
    enemy('mushmon', '蘑菇兽', 25, 'jam', '蘑菇孢子：目标下次攻击每段伤害－2。'),
    enemy('hagurumon', '齿轮兽', 28, 'shield', '防御充能：获得 10 护盾。'),
    enemy('picodevimon', '小恶魔兽', 24, 'buff', '恶作剧：对目标造成 8 伤害。'),
    enemy('bakemon', '猛鬼兽', 30, 'evade'),
    enemy('impmon', '小妖兽', 28, 'rapid', '恶作剧·双响：造成 8 伤害；目标生命低于一半时改为 14。'),
    enemy('devidramon', '邪龙兽', 65, 'charge'),
    enemy('dokugumon', '毒蜘蛛兽', 58, 'spider'),
    enemy('sinduramon', '铁鸡兽', 110, 'chicken'),
    enemy('ogremon', '奥加兽', 49, 'charge'),
    enemy('leomon', '狮子兽', 52, 'sword', '兽王咆哮：所有敌人虚弱 2，下次攻击每段伤害－2。'),
    enemy('andromon', '安杜路兽', 54, 'shield', '防御矩阵：获得 12 护盾。'),
    enemy('icedevimon', '冰恶魔兽', 82, 'jam'),
    enemy('vajramon', '蛮牛兽', 92, 'sword'),
    enemy('beelzebumon', '别西卜兽', 148, 'rapid'),
    {
      id: 'knightmon',
      name: '骑士兽',
      art: 'knightmon',
      hp: 44,
      style: 'expanded' as const,
      scan: true,
      guard: true,
    },
    {
      id: 'phantomon',
      name: '幻影兽',
      art: 'phantomon',
      hp: 46,
      style: 'expanded' as const,
      scan: true,
    },
    {
      id: 'kuramon',
      name: '库拉蒙',
      art: 'kuramon',
      hp: 18,
      style: 'expanded' as const,
      scan: true,
      onDeath: 'explode' as const,
    },
    {
      id: 'diaboromon',
      name: '超恶魔兽',
      art: 'diaboromon',
      hp: 168,
      style: 'expanded' as const,
      scan: false,
    },
    enemy('pawnchessmonblack', '兵棋兽（黑）', 30, 'charge'),
    enemy('pawnchessmonwhite', '兵棋兽（白）', 30, 'shield'),
    enemy('knightchessmonblack', '马棋兽（黑）', 40, 'expanded'),
    enemy('knightchessmonwhite', '马棋兽（白）', 40, 'expanded'),
    enemy('keramon', '哈哈兽', 34, 'jam', '数据啃噬：目标下次攻击每段伤害－2。'),
    enemy('chrysalimon', '虫蛹兽', 48, 'expanded'),
    {
      id: 'rookchessmon',
      name: '车棋兽',
      art: 'rookchessmon',
      hp: 85,
      style: 'expanded' as const,
      scan: true,
      guard: true,
    },
    {
      id: 'bishopchessmon',
      name: '相棋兽',
      art: 'bishopchessmon',
      hp: 75,
      style: 'expanded' as const,
      scan: true,
    },
    {
      id: 'infermon',
      name: '地狱兽',
      art: 'infermon',
      hp: 88,
      style: 'expanded' as const,
      scan: true,
    },
    {
      id: 'armageddemon',
      name: '灭世魔兽',
      art: 'armageddemon',
      hp: 110,
      style: 'expanded' as const,
      scan: true,
    },
    {
      id: 'lilithmon',
      name: '莉莉丝兽',
      art: 'lilithmon',
      hp: 92,
      style: 'expanded' as const,
      scan: true,
    },
    {
      id: 'leviamon',
      name: '利维坦兽',
      art: 'leviamon',
      hp: 108,
      style: 'expanded' as const,
      scan: true,
    },
    {
      id: 'grandracmon',
      name: '大德拉库兽',
      art: 'grandracmon',
      hp: 96,
      style: 'expanded' as const,
      scan: true,
    },
    {
      id: 'daemon',
      name: '究极魔兽',
      art: 'daemon',
      hp: 100,
      style: 'expanded' as const,
      scan: true,
    },
    {
      id: 'belphemon',
      name: '贝尔菲兽',
      art: 'belphemon',
      hp: 105,
      style: 'expanded' as const,
      scan: true,
    },
    {
      id: 'barbamon',
      name: '巴鲁巴兽',
      art: 'barbamon',
      hp: 95,
      style: 'expanded' as const,
      scan: true,
    },
    {
      id: 'lopmon',
      name: '黑大耳兽',
      art: 'lopmon',
      hp: 1,
      style: 'rapid' as const,
      scan: false,
      support: '安慰之光：清除手牌中 1 张故障牌；没有故障牌时回复 6 生命。',
    },
    ...['scout', 'replica', 'corrupt', 'sentinel', 'devourer', 'core'].map((id, i): EnemyDef => ({
      id,
      name: ['侦察代理体', '复制代理体', '侵蚀代理体', '护卫代理体', '吞噬代理体', '帝厉魔核心'][i],
      art: id,
      hp: [46, 48, 50, 90, 95, 190][i],
      style: (['rapid', 'buff', 'jam', 'shield', 'spider', 'core'] as const)[i],
      scan: false,
    })),
  ].map((e) => [e.id, e]),
);
export const RELICS: Record<string, { name: string; text: string }> = {
  reader: { name: '备用读卡器', text: '每场首回合多抽 1 张牌。' },
  cooler: { name: '散热芯片', text: '每回合前三次攻击伤害段＋1。' },
  firewall: { name: '防火模块', text: '每回合首次施加灼烧，获得 3 护盾。' },
  memory: { name: '记忆晶片', text: '战斗胜利后回复 3 生命。' },
  battery: { name: '应急电池', text: '每场首回合额外获得 1 行动力。' },
  armor: { name: '合金装甲', text: '每回合开始时获得 3 护盾。' },
  capacitor: { name: '噬能电容器', text: '每场战斗开始时获得 1 噬能。' },
  magazine: { name: '过载弹匣', text: '每场战斗开始时获得 1 蓄能。' },
  firebrand: { name: '火种徽章', text: '每场战斗首次施加灼烧，额外增加 1 层。' },
  compass: { name: '咒术罗盘', text: '每回合首次施加符印，额外增加 1 层。' },
  fang: { name: '吸血獠牙', text: '吸血卡的回复量＋1。' },
};
export const BLESSINGS: Record<string, { name: string; text: string }> = {
  bond: { name: '羁绊共鸣', text: '每场战斗开始时获得 2 同步值。' },
  guard: { name: '守护之心', text: '每回合第一张防御技能额外获得 3 护盾。' },
  growth: { name: '生命之光', text: '最大生命＋10，并回复 10 生命。' },
};
export const CHAPTERS = [
  { name: '现实的裂隙', subtitle: '新宿 · 黄昏边界', theme: 'city' },
  { name: '迷失的数据原野', subtitle: '数码世界 · 记忆森林', theme: 'forest' },
  { name: '钢铁回廊', subtitle: '机械禁区 · 流水线遗迹', theme: 'steel' },
  { name: '暗域深渊', subtitle: '病毒巢穴 · 低语深渊', theme: 'abyss' },
  { name: '最后的信号', subtitle: '侵蚀区域 · 帝厉魔核心', theme: 'void' },
];
export const PORTRAIT_FORMS = ['blackgrowmon', 'youkomon', 'doumon', 'blackgalgomon'];
export const asset = (id: string) =>
  `${import.meta.env.BASE_URL}${PORTRAIT_FORMS.includes(id) ? 'portraits/' + id + '.jpg' : 'sprites/' + id + '.png'}`;
export const cardText = (c: { id: string; upgraded: boolean }) => {
  const d = CARDS[c.id];
  if (!c.upgraded) return d.text;
  if (d.upgradeText) return d.upgradeText;
  let text = d.text;
  if (d.damage) text = text.replace(/造成 \d+/, `造成 ${d.damage + (d.upgradeDamage ?? 3)}`);
  if (d.shield) text = text.replace(/获得 \d+ (?:点)?护盾/, `获得 ${d.shield + 3} 护盾`);
  return text;
};
export const needsTarget = (d: CardDef) =>
  !d.all &&
  !!(
    d.damage ||
    d.mark ||
    d.burn ||
    d.weak ||
    d.devourVuln ||
    d.special === 'markburst' ||
    d.special === 'detonate'
  );

export const PARTNER_IDS = Object.keys(PARTNERS) as Partner[];
export const inheritanceOptions = (partner: Partner) =>
  partner === 'guilmon'
    ? ['ember', 'ward']
    : partner === 'renamon'
      ? ['seal', 'flow']
      : ['ward', 'flow'];
