export interface Encounter { id:string; chapter:number; name:string; enemies:string[]; opening?:boolean }
const encounter=(id:string,chapter:number,name:string,enemies:string[],opening=false):Encounter=>({id,chapter,name,enemies,opening});
// 人工安排角色组合，避免随机拼出多只干扰者或同种重复阵容。
export const ENCOUNTERS:Encounter[]=[
 encounter('city-ore',0,'矿石岗哨',['gotsumon'],true),
 encounter('city-electric',0,'水边电光',['betamon'],true),
 encounter('city-rush',0,'突击练习',['monodramon'],true),
 encounter('city-goblin',0,'街角挑战',['goblimon'],true),
 encounter('city-gears',0,'失控齿轮',['hagurumon'],true),
 encounter('city-shooters',0,'护盾与射手',['hagurumon','impmon']),
 encounter('city-cheer',0,'鼓舞与重击',['goblimon','picodevimon']),
 encounter('city-spores',0,'孢子伏击',['mushmon','betamon']),
 encounter('city-shadow',0,'幽影岗哨',['bakemon','gotsumon']),
 encounter('city-clock',0,'时间噪声',['clockmon','picodevimon']),
 encounter('wild-river',1,'深水来客',['seadramon'],true),
 encounter('wild-swords',1,'狮子兽的试炼',['leomon'],true),
 encounter('wild-armor',1,'机械哨站',['andromon'],true),
 encounter('wild-duet',1,'鼓舞与突击',['gekomon','monodramon']),
 encounter('wild-healer',1,'重锤与歌声',['ogremon','gekomon']),
 encounter('wild-tide',1,'潮汐与电流',['seadramon','betamon']),
 encounter('wild-time',1,'时钟守卫',['clockmon','gotsumon']),
 encounter('wild-fortress',1,'装甲火线',['andromon','impmon']),
 encounter('wild-trick',1,'术式训练',['leomon','picodevimon']),
 encounter('wild-ambush',1,'暗处的孢子',['mushmon','monodramon']),
 encounter('void-scout',2,'边界侦察',['scout'],true),
 encounter('void-copy',2,'镜像信号',['replica'],true),
 encounter('void-rot',2,'侵蚀残片',['corrupt'],true),
 encounter('void-watch',2,'哨戒与护甲',['scout','gotsumon']),
 encounter('void-repair',2,'复制与修复',['replica','gekomon']),
 encounter('void-noise',2,'侵蚀与鼓舞',['corrupt','picodevimon']),
 encounter('void-clock',2,'错位时序',['clockmon','monodramon']),
 encounter('void-flood',2,'数据洪流',['seadramon','hagurumon']),
 encounter('void-guard',2,'残存的守卫',['andromon','betamon']),
 encounter('void-shadow',2,'幽影追踪',['bakemon','scout']),
];
