import { ExplorationMap } from './components/ExplorationMap';
import { EvolutionTree, EvolutionTracker } from './components/EvolutionTree';
import { ItemCodex } from './components/ItemCodex';
import { DeckViewer } from './components/DeckViewer';
import type { Pile } from './components/DeckViewer';
import { EVOLUTIONS, ROUTE_DATA, stageLimit, stageName } from './game/evolution';
import { useCallback, useEffect, useReducer, useRef, useState } from 'react';
import type { ReactNode } from 'react';
import { ArrowRight, ArrowUpRight, ArrowLeft, Heart, Shield, Zap, Swords, ScanLine, GitBranch, BookOpen, Backpack, Settings, X, ChevronDown, Coins, Flame, Sparkles, Check, Lock, Tent, ShoppingBag, Radio, Box, Volume2, VolumeX, Download, Play, CircleHelp, RotateCcw, Layers, Crosshair, Activity } from 'lucide-react';
import { GameCard } from './components/GameCard';
import { Sprite } from './components/Sprite';
import { BLESSINGS, BRANCHES, CARDS, CHAPTERS, ENEMIES, FORM_NAMES, PARTNERS, PARTNER_IDS, RELICS, asset } from './game/data';
import { cardCost, intent, reduceGame } from './game/engine';
import { loadSave, SAVE_KEY, writeSave } from './game/storage';
import type { Action, Card, Partner } from './game/types';
const inheritance={ember:'余烬：首次施加灼烧额外＋1',ward:'坚守：首次防御额外＋2 护盾',seal:'符心：第一张牌施加符印时额外＋1',flow:'灵巧：第一张牌为技能时获得 2 护盾'};
type BattleMotion = {actor:'player'|'enemy';enemyIds:string[];phase:'windup'|'impact';playerHit:boolean};
function Modal({title,children,onClose,wide=false}:{title:string;children:ReactNode;onClose:()=>void;wide?:boolean}){
 const ref=useRef<HTMLDivElement>(null);
 useEffect(()=>{const before=document.activeElement;ref.current?.focus();const handle=(e:KeyboardEvent)=>{if(e.key==='Escape')onClose();if(e.key==='Tab'){const items=ref.current?.querySelectorAll<HTMLElement>('button:not(:disabled),a[href],input,select');if(!items?.length)return;const first=items[0],last=items[items.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}};document.addEventListener('keydown',handle);return()=>{document.removeEventListener('keydown',handle);if(before instanceof HTMLElement)before.focus();};},[onClose]);
 return <div className="modal-backdrop" onClick={onClose}><div className={`modal ${wide?'wide-modal':''}`} role="dialog" aria-modal="true" aria-label={title} ref={ref} tabIndex={-1} onClick={e=>e.stopPropagation()}><div className="modal-heading"><h2>{title}</h2><button className="icon-btn" onClick={onClose} aria-label="关闭"><X/></button></div>{children}</div></div>;
}
function Health({hp,max,block=0}:{hp:number;max:number;block?:number}){return <div className="health"><div className="health-track"><i style={{width:`${100*hp/max}%`}}/></div><span><Heart size={12}/>{hp}<small>/{max}</small>{block>0&&<b><Shield size={12}/>{block}</b>}</span></div>;}
function SceneDecor({theme}:{theme:string}){return <div className={`scene-decor ${theme}`} aria-hidden="true"><div className="scene-moon"/><div className="horizon h1"/><div className="horizon h2"/><div className="scene-grid"/><i className="particle p1"/><i className="particle p2"/><i className="particle p3"/><i className="particle p4"/></div>;}
export default function App(){
 const [initial]=useState(loadSave);const [state,dispatch]=useReducer(reduceGame,initial.save);const [saveError,setSaveError]=useState(initial.error);const [screen,setScreen]=useState<'home'|'game'>(()=>initial.save.run&&initial.save.run.screen!=='result'?'game':'home');
 const [modal,setModal]=useState<'deck'|'collection'|'items'|'tree'|'settings'|'help'|'abandon'|null>(null);const [selected,setSelected]=useState<string|null>(null);const [target,setTarget]=useState<string|null>(null);const [campMode,setCampMode]=useState<'upgrade'|'remove'|null>(null);const [deckPile,setDeckPile]=useState<Pile>('deck');
 const [motion,setMotion]=useState<BattleMotion|null>(null);const [battleBusy,setBattleBusy]=useState(false);const busyRef=useRef(false);const timers=useRef<number[]>([]);const sequence=useRef(0);const enemyStepKey=useRef('');
 const audio=useRef<AudioContext|null>(null);const r=state.run,b=r?.battle;const isActive=!!r&&r.screen!=='result';
 useEffect(()=>{if(initial.error&&state===initial.save)return;setSaveError(writeSave(state));},[state,initial]);
 useEffect(()=>{document.body.classList.toggle('reduce-motion',state.settings.reducedMotion);},[state.settings.reducedMotion]);
 useEffect(()=>()=>{sequence.current++;timers.current.forEach(clearTimeout);timers.current=[];},[]);
 const send=useCallback((action:Action)=>{
  if(state.settings.sound){try{audio.current??=new AudioContext();void audio.current.resume();const osc=audio.current.createOscillator(),gain=audio.current.createGain();osc.connect(gain);gain.connect(audio.current.destination);osc.type='sine';osc.frequency.value=action.type==='play'?440:620;gain.gain.setValueAtTime(.035,audio.current.currentTime);gain.gain.exponentialRampToValueAtTime(.001,audio.current.currentTime+.12);osc.start();osc.stop(audio.current.currentTime+.13);}catch{setSaveError('声音无法播放，游戏仍可继续。');}}
  dispatch(action);setSelected(null);if(action.type==='node'){setTarget(null);setCampMode(null);}if(action.type==='start')setScreen('game');
 },[state.settings.sound]);
 const queueAction=useCallback((action:Action,actor:BattleMotion['actor'],enemyIds:string[]=[],playerHit=false)=>{
  if(busyRef.current)return;
  if(state.settings.reducedMotion||window.matchMedia('(prefers-reduced-motion: reduce)').matches){send(action);return;}
  busyRef.current=true;setBattleBusy(true);
  const current=++sequence.current;
  const schedule=(callback:()=>void,delay:number)=>{timers.current.push(window.setTimeout(()=>{if(sequence.current===current)callback();},delay));};
  setMotion({actor,enemyIds,phase:'windup',playerHit});
  schedule(()=>{setMotion({actor,enemyIds,phase:'impact',playerHit});schedule(()=>{send(action);schedule(()=>{setMotion(null);busyRef.current=false;setBattleBusy(false);timers.current=[];},160);},140);},170);
 },[send,state.settings.reducedMotion]);
 useEffect(()=>{
  if(r?.screen!=='battle'||!b||b.enemyTurnIndex===null||battleBusy)return;
  const key=`${state.meta.games}-${r.currentNode?.id}-${b.turn}-${b.enemyTurnIndex}`;
  if(enemyStepKey.current===key)return;
  enemyStepKey.current=key;
  if(b.enemyTurnIndex>=b.enemies.length){dispatch({type:'finishEnemyTurn'});return;}
  const enemy=b.enemies[b.enemyTurnIndex];
  if(enemy.hp<=0){dispatch({type:'enemyStep'});return;}
  queueAction({type:'enemyStep'},'enemy',[enemy.uid],intent(r,enemy).type==='attack');
 },[r,b,battleBusy,queueAction,state.meta.games]);
 function start(partner:Partner){if(initial.error){try{const original=localStorage.getItem(SAVE_KEY);if(original)localStorage.setItem(`${SAVE_KEY}-recovery-${Date.now()}`,original);}catch{setSaveError('旧存档备份失败。');return;}}send({type:'start',partner});}
 const chapter=r?CHAPTERS[Math.min(2,Math.floor(r.row/8))]:CHAPTERS[0];
 const activeCard=b?.hand.find(c=>c.uid===selected);const activeEnemy=b?.enemies.find(e=>e.uid===target&&e.hp>0)??b?.enemies.find(e=>e.hp>0);
 const battleLocked=battleBusy||b?.enemyTurnIndex!==null;
 function playSelectedCard(){if(!activeCard||!b||battleLocked||cardCost(activeCard)>b.energy)return;const definition=CARDS[activeCard.id];const canHit=!!definition.damage||['detonate','markburst','shieldhit','cannon'].includes(definition.special??'');const enemyIds=canHit?(definition.all?b.enemies.filter(e=>e.hp>0).map(e=>e.uid):activeEnemy?[activeEnemy.uid]:[]):[];queueAction({type:'play',uid:activeCard.uid,target:activeEnemy?.uid},'player',enemyIds);}
 const sample=(id:string):Card=>({uid:id,id,upgraded:false});
 const closeModal=useCallback(()=>setModal(null),[]);
 function openDeck(pile:Pile='deck'){setDeckPile(pile);setModal('deck');}
 return <div className="app-shell">
  <header className="topbar"><button className="brand" onClick={()=>setScreen('home')} aria-label="返回首页"><span className="brand-symbol"><ScanLine size={23}/></span><span>数码旅途<small>DIGITAL ODYSSEY</small></span></button><nav>{screen==='home'&&r&&<button className="icon-btn" aria-label="查看卡组" onClick={()=>openDeck()}><Layers size={18}/></button>}<button className="icon-btn" aria-label="查看进化树" onClick={()=>setModal('tree')}><GitBranch size={18}/></button><button className="icon-btn collection-entry" title="伙伴图鉴" aria-label={`伙伴图鉴，已转化 ${state.meta.partners.length} 位伙伴`} onClick={()=>setModal('collection')}><BookOpen size={18}/><b aria-hidden="true">{state.meta.partners.length}</b></button><button className="icon-btn" title="道具图鉴" aria-label="道具图鉴" onClick={()=>setModal('items')}><Backpack size={19}/></button><button className="icon-btn" aria-label="玩法说明" onClick={()=>setModal('help')}><CircleHelp size={19}/></button><button className="icon-btn" aria-label="设置" onClick={()=>setModal('settings')}><Settings size={19}/></button></nav></header>
  {saveError&&<div className="save-warning" role="alert">{saveError}</div>}
  {screen==='home'?<main className="home">
   <div className="home-copy"><div className="eyebrow"><span className="signal-dot"/> 与搭档，再次连接</div><h1>每一次选择，<br/>都是新的<span>进化。</span></h1><p>跨越现实与数码世界。<br/>抽换你的卡片，寻找属于你们的进化路线。</p><div className="home-tags"><span><Swords size={15}/>卡牌构筑</span><span><GitBranch size={15}/>分支进化</span><span><ScanLine size={15}/>扫描伙伴</span></div>{isActive&&<button className="primary continue-btn" onClick={()=>setScreen('game')}><Play size={18}/>继续冒险 <span>第 {Math.floor(r.row/8)+1} 章 · {FORM_NAMES[r.form]}</span><ArrowRight size={18}/></button>}<div className="home-meta"><span>单人冒险</span><i/><span>自动保存</span><i/><span>手机竖屏</span></div></div>
   <div className="hero-art"><SceneDecor theme="forest"/><div className="orbit orbit-a"/><div className="orbit orbit-b"/><div className="hero-label"><span>LINK ESTABLISHED</span><b>同步，始于信任。</b></div><Sprite id="guilmon" size={340} className="hero-guilmon"/><Sprite id="renamon" size={330} className="hero-renamon"/><Sprite id="terriermon" size={190} className="hero-terriermon"/><span className="hero-coordinate">35° 41′ N / DIGITAL FIELD</span></div>
   <section className="partner-section"><div className="section-heading"><div><span className="eyebrow">01 / SELECT PARTNER</span><h2>选择你的搭档</h2></div><p>不同搭档，同样无限的可能。</p></div><div className="partner-grid">{PARTNER_IDS.map((id,i)=><button className={`partner-pick ${id}`} key={id} onClick={()=>start(id)} disabled={isActive}><div className="partner-number">0{i+1}</div><Sprite id={id} size={180}/><div className="partner-description"><span className="eyebrow">{PARTNERS[id].tag}</span><h3>{PARTNERS[id].name}</h3><p>{PARTNERS[id].description}</p><div className="route-mini">{PARTNERS[id].branches.map(key=><span key={key}>{BRANCHES[key].name}</span>)}</div><span className="pick-link">{isActive?'当前旅途尚未结束':'与我一起出发'}<ArrowUpRight size={18}/></span></div></button>)}</div>{isActive&&<button className="text-btn" onClick={()=>setModal('abandon')}>结束当前旅途，重新选择搭档</button>}</section>
   <footer className="home-footer"><span>每一段旅程，都会留下数据与回忆。</span><span>本地试玩版 0.2 · {state.meta.wins} 次完成旅途</span></footer>
  </main>:r&&<main className="game-layout">
   <aside className="journey-sidebar"><div className="eyebrow">YOUR JOURNEY</div><h2>{chapter.name}</h2><p>{chapter.subtitle}</p><div className="chapter-steps">{CHAPTERS.map((ch,i)=><div key={ch.name} className={i===Math.floor(r.row/8)?'current':i<Math.floor(r.row/8)?'completed':''}><span>{i<Math.floor(r.row/8)?<Check size={13}/>:String(i+1).padStart(2,'0')}</span><div>{ch.name}<small>{i===Math.floor(r.row/8)?`${r.row%8+1} / 8 节点`:i<Math.floor(r.row/8)?'已穿越':'等待连接'}</small></div></div>)}</div><div className="sidebar-note"><Radio size={20}/><p>选牌塑造战术，<br/>进化决定可能。</p></div><button className="secondary" onClick={()=>setModal('tree')}><GitBranch size={16}/>查看进化路线</button><button className="text-btn" onClick={()=>setScreen('home')}><ArrowLeft size={14}/>返回首页 · 进度已保存</button></aside>
   <section className={`game-main ${r.screen==='battle'?'is-battle':''}`}>
    <div className="run-status"><div className="status-chapter"><span className="eyebrow">CHAPTER 0{Math.floor(r.row/8)+1}</span><b>{r.screen==='battle'?`第 ${b?.turn??1} 回合`:chapter.name}</b></div><div className="run-resources"><span title="生命"><Heart size={16}/>{r.hp}<small>/{r.maxHp}</small></span><span title="金币"><Coins size={16}/>{r.gold}</span><button aria-label="查看牌组" onClick={()=>openDeck()}><Layers size={17}/><span>卡组</span> {r.deck.length}</button></div></div>
    <EvolutionTracker run={r} meta={state.meta} onOpen={()=>setModal('tree')}/>{r.screen==='map'&&<ExplorationMap run={r} onEnter={id=>send({type:'node',id})} onTree={()=>setModal('tree')}/>}
    {r.screen==='battle'&&b&&<div className="battle-view"><div className={`battle-stage ${chapter.theme}`}><SceneDecor theme={chapter.theme}/><div className="battle-topline"><span><Crosshair size={13}/>{r.currentNode?.kind==='boss'?'首领战':r.currentNode?.kind==='elite'?'精英遭遇':'数码遭遇'}</span><span>{b.enemyTurnIndex!==null?'敌方行动中':'点击敌人选择目标'}</span></div><div className="enemies">{b.enemies.map(e=>{const plan=intent(r,e);return <button key={e.uid} className={`enemy ${e.hp<=0?'defeated':''} ${activeEnemy?.uid===e.uid?'targeted':''} ${motion?.actor==='enemy'&&motion.enemyIds.includes(e.uid)&&motion.phase==='windup'?'acting':''} ${motion?.actor==='player'&&motion.enemyIds.includes(e.uid)&&motion.phase==='impact'?'taking-hit':''}`} onClick={()=>setTarget(e.uid)} disabled={e.hp<=0||battleLocked} aria-label={`选择目标 ${ENEMIES[e.id].name}`}><span className={`enemy-intent ${plan.type}`} title={plan.detail}>{plan.type==='attack'?<Swords size={14}/>:plan.type==='block'?<Shield size={14}/>:<Sparkles size={14}/>} {plan.name}{plan.type==='attack'&&<b>{plan.damage}{plan.hits>1?`×${plan.hits}`:''}</b>}{plan.shield>0&&<b>{plan.shield}</b>}</span><Sprite id={e.id} size={b.enemies.length>1?175:200}/><span className="enemy-name">{ENEMIES[e.id].name}</span><Health hp={e.hp} max={e.maxHp} block={e.block}/><span className="status-tags">{e.burn>0&&<span><Flame size={12}/>{e.burn}</span>}{e.mark>0&&<span><Sparkles size={12}/>{e.mark}</span>}{e.weakened>0&&<span>虚弱 {e.weakened}</span>}{e.hp<=0&&<span>已击败</span>}</span></button>;})}</div><div className="player-field"><div className={`player-unit ${motion?.actor==='player'&&motion.phase==='windup'?'acting':''} ${motion?.actor==='enemy'&&motion.phase==='impact'&&motion.playerHit?'taking-hit':''}`}><Sprite id={r.form} size={210}/><div className="player-caption"><strong>{FORM_NAMES[r.form]}</strong><span>{r.branch?BRANCHES[r.branch].tag:r.training==='defense'&&r.stage>0?'守护训练':'与你并肩'}</span><Health hp={r.hp} max={r.maxHp} block={b.block}/></div></div><div className="sync-device"><div className="sync-dial"><ScanLine size={23}/><b>{b.sync}<small>/6</small></b></div><span>同步率</span><button disabled={battleLocked||!r.branch||b.sync<6||b.burstUsed} onClick={()=>send({type:'burst'})}>{b.burst>0?`爆发 · ${b.burst} 回合`:b.burstUsed?'本场已爆发':r.branch?'同步爆发':'究极体解锁'}</button></div></div>{b.burst>0&&<div className="burst-banner">同步爆发 · 攻击每段＋2</div>}<div className="battle-log" key={`${b.turn}-${b.played}-${b.log[0]}`} aria-live="polite">{b.log[0]}</div></div>
     <div className="combat-info"><span><Shield size={14}/>护盾 {b.block}</span>{b.strength>0&&<span><Swords size={14}/>力量 {b.strength}</span>}{b.charge>0&&<span><Zap size={14}/>蓄能 {b.charge}</span>}<button className="text-btn" onClick={()=>setModal('help')}>状态说明<CircleHelp size={13}/></button></div>
     <div className="hand-heading"><span><span className="energy-gem">{b.energy}</span>行动力<small>每回合恢复 3 点</small></span><span className="pile-info"><button onClick={()=>openDeck('draw')}>抽牌 {b.draw.length}</button><button onClick={()=>openDeck('discard')}>弃牌 {b.discard.length}</button><button onClick={()=>openDeck('exhaust')}>耗竭 {b.exhaust.length}</button></span></div>
     <div className="hand">{b.hand.map(c=><GameCard run={r} key={c.uid} card={c} selected={selected===c.uid} disabled={battleLocked} onClick={()=>selected===c.uid?playSelectedCard():setSelected(c.uid)}/>)}{!b.hand.length&&<p className="empty-hand">手牌已用尽，结束回合抽取新牌。</p>}</div>
     <div className="battle-actions"><button className="support-btn" disabled={battleLocked||b.supportUsed} onClick={()=>send({type:'support',target:activeEnemy?.uid})}><ScanLine size={17}/><span>{ENEMIES[r.support]?.name??'应急防御'}<small>{b.supportUsed?'本场已使用':r.support==='mushmon'?'虚弱目标':r.support==='picodevimon'?'8 点伤害':r.support==='hagurumon'?'+10 护盾':'+8 护盾'}</small></span></button><button className="potion-btn" disabled={battleLocked||!r.potions||r.hp>=r.maxHp} onClick={()=>send({type:'potion'})} aria-label={`使用恢复磁盘，剩余${r.potions}个`}><Heart size={18}/><b>{r.potions}</b></button><div className="turn-buttons"><button className="secondary use-card" disabled={!activeCard||battleLocked||cardCost(activeCard)>b.energy} onClick={playSelectedCard} aria-label={activeCard?`使用 ${CARDS[activeCard.id].name}`:'选择卡片后使用'}><Zap size={16}/>使用</button><button className="primary end-turn" disabled={battleLocked} onClick={()=>send({type:state.settings.reducedMotion||window.matchMedia('(prefers-reduced-motion: reduce)').matches?'endTurn':'beginEnemyTurn'})}>结束回合<ArrowRight size={17}/></button></div></div>
    </div>}
    {r.screen==='reward'&&r.reward&&<div className="choice-screen reward-screen"><div className="result-symbol"><Check size={28}/></div><span className="eyebrow">CONNECTION RESTORED</span><h1>漂亮的配合。</h1><p>选择一张卡牌，继续构筑你的可能。</p><div className="reward-badges"><span><Coins size={16}/>＋{r.reward.gold}</span>{r.reward.relic&&<span><Box size={16}/>{RELICS[r.reward.relic].name}</span>}</div><div className="activity-reward">{r.reward.gains?.map(g=><span key={g}>{g}</span>)}{r.reward.unlocks?.map(id=><strong key={id}>永久解锁：{ROUTE_DATA[id].name}</strong>)}</div><div className="reward-cards">{r.reward.cards.map(id=><div key={id}><GameCard run={r} card={sample(id)} onClick={()=>send({type:'reward',card:id})}/><button className="text-btn" onClick={()=>send({type:'reward',card:id})}>加入牌组<ArrowRight size={14}/></button></div>)}</div><div className="scan-results">{r.reward.scans.map(scan=><div key={scan.id}><img src={asset(scan.id)} alt=""/><div><b>{ENEMIES[scan.id].name}</b><span>扫描 {scan.before}% → {scan.after}%</span><progress max={100} value={scan.after}/></div>{ENEMIES[scan.id].support&&scan.after===100&&!state.meta.partners.includes(scan.id)?<button className="secondary" onClick={()=>send({type:'convert',id:scan.id})}>转化伙伴</button>:<span className="scan-note">{state.meta.partners.includes(scan.id)?'已转化':scan.after===100?'资料完整':'数据已保存'}</span>}</div>)}</div><button className="secondary" onClick={()=>send({type:'reward'})}>跳过卡牌，继续<ArrowRight size={15}/></button></div>}
    {r.screen==='blessing'&&<div className="choice-screen"><Sparkles className="large-icon"/><span className="eyebrow">A LITTLE LIGHT FOR THE JOURNEY</span><h1>{r.currentNode?'新的力量，新的旅途。':'带上一份祝福。'}</h1><p>{r.currentNode?'选择新祝福，替换当前祝福。':'选择一种祝福，陪伴这次冒险。'}</p><div className="option-list">{Object.entries(BLESSINGS).map(([id,d])=><button key={id} className="option" onClick={()=>send({type:'bless',id})}><span className="option-icon">{id==='bond'?<Activity/>:id==='guard'?<Shield/>:<Heart/>}</span><span><strong>{d.name}</strong><small>{d.text}</small></span><ArrowRight size={18}/></button>)}</div></div>}
    {r.screen==='camp'&&<div className="choice-screen camp-screen"><Tent className="large-icon"/><span className="eyebrow">REST / RECONNECT</span><h1>在这里，喘口气。</h1><p>夜色很安静，搭档正期待你的决定。</p><Sprite id={r.form} size={200}/>{campMode==='upgrade'?<><h3>选择一张牌强化</h3><div className="deck-grid">{r.deck.filter(c=>!c.upgraded).map(c=><GameCard run={r} compact key={c.uid} card={c} onClick={()=>send({type:'camp',mode:'upgrade',uid:c.uid})}/>)}</div><button className="text-btn" onClick={()=>setCampMode(null)}>返回</button></>:<div className="option-list"><button className="option" onClick={()=>send({type:'camp',mode:'heal'})}><Heart/><span><strong>休息与修复</strong><small>回复 {Math.ceil(r.maxHp*.3)} 生命 · 当前 {r.hp}/{r.maxHp}</small></span><ArrowRight/></button><button className="option" disabled={r.deck.every(c=>c.upgraded)} onClick={()=>setCampMode('upgrade')}><Zap/><span><strong>练习卡片抽换</strong><small>永久强化本局牌组中的一张卡牌</small></span><ArrowRight/></button>{r.stage<stageLimit(r)&&<button className="option" onClick={()=>send({type:'campEvolution'})}><GitBranch/><span><strong>补上进化</strong><small>选择已满足条件的下一阶段形态，消耗本次营地行动</small></span><ArrowRight/></button>}</div>}</div>}
    {r.screen==='shop'&&<div className="choice-screen"><ShoppingBag className="large-icon"/><span className="eyebrow">THE WANDERING TRADER</span><h1>旅途中的补给。</h1><p>有时，少一张牌会比多一张更强。</p><div className="reward-cards">{r.shopStock.map(id=><div key={id}><GameCard run={r} card={sample(id)} onClick={()=>send({type:'buy',id})} disabled={r.gold<45||r.shopBought.includes(id)}/><span className="price">{r.shopBought.includes(id)?'已购入':'45 金币'}</span></div>)}</div><div className="shop-tools"><button className="option" disabled={r.gold<30||r.potions>=2||r.shopBought.includes('potion')} onClick={()=>send({type:'buy',id:'potion'})}><Heart/><span><strong>恢复磁盘</strong><small>回复 18 生命 · 30 金币</small></span></button><button className="option" disabled={r.gold<80||r.shopBought.includes('relic')} onClick={()=>send({type:'buy',id:'relic'})}><Box/><span><strong>未知装置</strong><small>获得随机装置 · 80 金币</small></span></button><button className="option" disabled={r.gold<45||r.shopRemoved||r.deck.length<=5} onClick={()=>setCampMode(campMode==='remove'?null:'remove')}><Layers/><span><strong>精简牌组</strong><small>移除一张卡牌 · 45 金币</small></span></button></div>{campMode==='remove'&&!r.shopRemoved&&<div className="deck-grid">{r.deck.map(c=><GameCard run={r} key={c.uid} compact card={c} onClick={()=>{send({type:'remove',uid:c.uid});setCampMode(null);}}/>)}</div>}<button className="secondary" onClick={()=>send({type:'continue'})}>离开商店<ArrowRight size={16}/></button></div>}
    {r.screen==='event'&&<div className="choice-screen event-screen"><Radio className="large-icon"/><span className="eyebrow">AN UNEXPECTED SIGNAL</span><h1>废墟里的一束光。</h1><div className="event-illustration"><ScanLine size={64}/><span>DATA RECOVERY / 68%</span></div><p className="story-text">一台损坏的读卡器仍在发出微弱信号。<br/>搭档看向你。你们可以修复它，也可以在这里短暂休息。</p><div className="option-list"><button className="option" onClick={()=>send({type:'event',choice:'risk'})}><Zap/><span><strong>尝试修复</strong><small>失去 8 生命（最低保留 1），获得 35 金币，强化一张未强化的非防御插件牌。</small></span><ArrowRight/></button><button className="option" onClick={()=>send({type:'event',choice:'safe'})}><Heart/><span><strong>{Math.floor(r.row/8)===1?'休息与研究':'一起休息'}</strong><small>回复 10 生命。{Math.floor(r.row/8)===1?'研究并净化信号，永久解锁净化资料与机械研究。':''}</small></span><ArrowRight/></button></div></div>}
    {r.screen==='treasure'&&<div className="choice-screen"><Box className="large-icon"/><span className="eyebrow">A GIFT FROM THE DIGITAL WORLD</span><h1>被遗忘的数据。</h1><p>{r.message}</p><div className="treasure-art"><Box size={88}/></div>{r.relics.length>0&&<p>{RELICS[r.relics[r.relics.length-1]]?.text}</p>}<button className="primary" onClick={()=>send({type:'continue'})}>收好，继续前进<ArrowRight size={17}/></button></div>}
    {r.screen==='evolution'&&<div className="new-evolution-screen"><div className="screen-heading"><span className="eyebrow">DIGIVOLUTION / YOUR CHOICE</span><h1>你们，可以成为谁？</h1><p>{r.evolutionReturn==='camp'?'补进化会消耗本次营地行动；返回不会消耗。':'选择满足条件的下一阶段形态，也可以暂缓，在营地完成。'}</p></div><EvolutionTree key={`${r.form}-${r.evolutionReturn}`} run={r} meta={state.meta} choose onAction={send} onDeck={()=>openDeck()}/></div>}
    {r.screen==='result'&&<div className="choice-screen final-screen"><span className="eyebrow">{r.won?'UNTIL OUR NEXT ADVENTURE':'THE SIGNAL NEVER FADES'}</span><h1>{r.won?'旅途终点，也是起点。':'这一次，先休息吧。'}</h1><Sprite id={r.form} size={270}/><h2>{FORM_NAMES[r.form]}</h2><p>{r.won?'你们守住了最后的信号。下一次，会选择不同的进化吗？':'搭档的故事还会继续。已获取的扫描数据与伙伴不会丢失。'}</p><div className="run-summary"><span><b>{r.won?24:r.row+1}</b>探索节点</span><span><b>{r.kills}</b>击败敌人</span><span><b>{r.damageDealt}</b>累计伤害</span></div><button className="primary" onClick={()=>setScreen('home')}>开启下一段旅途<ArrowRight size={17}/></button><button className="text-btn" onClick={()=>setModal('collection')}>看看这次收集的伙伴<ScanLine size={15}/></button></div>}
   </section>
   <aside className="partner-sidebar"><div className="eyebrow">PARTNER LINK</div><Sprite id={r.form} size={170}/><h2>{FORM_NAMES[r.form]}</h2><p>{r.branch?BRANCHES[r.branch].tag:['成长期','成熟期','完全体'][r.stage]}</p><Health hp={r.hp} max={r.maxHp}/>{r.stage>0&&<div className="passive-note"><GitBranch size={16}/><span>{EVOLUTIONS[r.form]?.passive}<small>{inheritance[r.inherit]}</small></span></div>}<div className="aside-section"><h3><Sparkles size={15}/>旅途祝福</h3><p>{BLESSINGS[r.blessing]?.name??'等待选择'}</p><small>{BLESSINGS[r.blessing]?.text}</small></div><div className="aside-section"><h3><Backpack size={15}/>装置 <span>{r.relics.length}</span></h3>{r.relics.map(id=><div className="relic-item" key={id}><Box size={15}/><span>{RELICS[id].name}<small>{RELICS[id].text}</small></span></div>)}{!r.relics.length&&<small>精英与宝箱中藏着特别的力量。</small>}</div><button className="secondary" onClick={()=>setModal('collection')}><ScanLine size={16}/>{ENEMIES[r.support]?.name??'应急防御程序'}<ChevronDown size={15}/></button><small className="saved-indicator"><span className="signal-dot"/>{saveError?'存档需要处理':'冒险进度已保存'}</small></aside>
  </main>}
  {modal==='deck'&&r&&<Modal title={`卡组与牌堆 · ${r.deck.length} 张`} onClose={closeModal} wide><DeckViewer key={deckPile} run={r} initialPile={deckPile}/></Modal>}
  {modal==='collection'&&<Modal title="扫描与伙伴图鉴" onClose={closeModal}><details className="partner-codex"><summary>搭档形态 · {Object.keys(EVOLUTIONS).length} 种</summary><p className="modal-note">三位初始搭档直接可选；进化形态通过本局成长获得。扫描用于支援伙伴与跨局路线研究。</p><div className="collection-grid">{Object.values(EVOLUTIONS).map(form=><div className="collection-item" key={form.id}><img src={asset(form.id)} alt={FORM_NAMES[form.id]}/><h3>{FORM_NAMES[form.id]}</h3><span>{stageName(form.stage)}</span><p>{form.stage===0?'初始搭档 · 可直接选择':state.meta.discovered.includes(form.id)||r?.formHistory.includes(form.id)?'已到达此形态':'等待进化探索'}</p></div>)}</div><button className="secondary" onClick={()=>setModal('tree')}>查看进化路线<GitBranch size={16}/></button></details><p className="modal-note">战胜普通／精英数码兽＋50% 扫描。三个支援伙伴达到 100% 即可转化；每场支援一次，战斗外可更换。</p>{r&&<button className={`option ${r.support==='default'?'chosen':''}`} disabled={r.screen==='battle'} onClick={()=>send({type:'equip',id:'default'})}><Shield/><span><strong>应急防御程序</strong><small>每场一次，获得 8 护盾。</small></span>{r.support==='default'?<Check/>:<span>装备</span>}</button>}<div className="collection-grid">{Object.values(ENEMIES).filter(e=>e.scan).map(e=>{const progress=state.meta.scans[e.id]??0;const owned=state.meta.partners.includes(e.id);return <div className={`collection-item ${progress===0?'undiscovered':''}`} key={e.id}><img src={asset(e.id)} alt={e.name}/><h3>{e.name}</h3><span>{progress}% <small>{e.support?'支援伙伴':'资料图鉴'}</small></span><progress max={100} value={progress}/><p>{e.support??'收集战斗资料，记录你们的相遇。'}</p>{e.support&&(owned?<button className="secondary" disabled={!r||r.screen==='battle'||r.support===e.id} onClick={()=>send({type:'equip',id:e.id})}>{r?.support===e.id?'已装备':r?.screen==='battle'?'战斗后可更换':'装备支援'}</button>:<button className="secondary" disabled={progress<100} onClick={()=>send({type:'convert',id:e.id})}>{progress<100?<><Lock size={13}/>扫描未完成</>:'转化伙伴'}</button>)}</div>;})}</div></Modal>}
  {modal==='items'&&<Modal title="道具图鉴" onClose={closeModal} wide><ItemCodex run={isActive?r:null}/></Modal>}
  {modal==='tree'&&<Modal title="进化路线与条件" onClose={closeModal} wide><EvolutionTree run={r} meta={state.meta} onAction={send}/></Modal>}
  {modal==='help'&&<Modal title="驯兽师手册" onClose={closeModal}><div className="help-content"><h3>每回合怎么做？</h3><p>先看敌人意图 → 点击卡牌查看详情 → 点击敌人选择目标 →「卡片抽换」。每回合恢复 3 行动力，抽 5 张牌；手牌最多 8 张，抽牌堆用尽会洗回弃牌。</p><h3>护盾、灼烧、符印</h3><p>护盾优先承伤，在你的下回合开始清空。灼烧在敌人行动后造成等层数伤害，再减 1 层。符印由「解印」等卡牌消耗，每层追加伤害。耗竭牌本场不再抽到。</p><h3>路线与条件</h3><p>地图起点在下、首领在上，只能沿连线前进。进化树向右展开；阶段、前置形态、各行行为条件与永久资料需同时满足，同一行“或”满足一项即可。可设定目标追踪。未完成的进化可在营地消耗一次行动补上。</p><h3>行为计数</h3><p>成功出牌才计数：多段、群攻均计一次，技能次数包含强化牌。防御只计算主动出牌，自损与恢复须实际生效。每场每类最多10次，指定卡牌系列最多3次；复制牌不计入指定系列。胜利结算展示本场进度。新局重置行为次数，混沌／净化资料跨局保留。</p><h3>同步与进化</h3><p>每打出一张牌获得 1 同步，每回合最多 3。究极体可消耗 6 同步，开启三回合攻击每段＋2的爆发，并获得强化必杀牌，每场一次。爆发结束不会退化。进化保留到本局结束。</p><h3>扫描与续玩</h3><p>胜利后保存物种扫描度，同场同种只计一次。扫描满 100% 可转化齿轮兽、蘑菇兽、小恶魔兽为支援伙伴。本局失败保留图鉴；换浏览器不会自动同步存档。</p><h3>专属与继承技能</h3><p>通用卡可由任何形态使用。专属技能需在本局到达卡面对应形态后，才会出现在奖励与商店；后续进化仍可使用，标为「继承技能」。未走过的分支不会自动解锁。旧版已经取得的卡牌保留可用，但不会提前再次掉落。</p><h3>状态与强化</h3><p>力量增加每段攻击伤害。蓄能由脉冲炮消耗。卡牌强化使伤害／护盾＋3；没有伤害与护盾的功能牌费用－1。敌人的「电荷反应」会随当回合出牌数量增加伤害。</p></div></Modal>}
  {modal==='settings'&&<Modal title="旅途设置" onClose={closeModal}><div className="option-list"><button className="option" onClick={()=>send({type:'settings',key:'sound'})}>{state.settings.sound?<Volume2/>:<VolumeX/>}<span><strong>操作音效</strong><small>{state.settings.sound?'已开启':'已关闭'}</small></span></button><button className="option" onClick={()=>send({type:'settings',key:'reducedMotion'})}><Activity/><span><strong>减少动态效果</strong><small>{state.settings.reducedMotion?'已开启':'已关闭'}</small></span></button><button className="option" onClick={()=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='数码旅途-存档备份.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}}><Download/><span><strong>下载存档备份</strong><small>保存当前冒险与图鉴数据</small></span></button></div><p className="modal-note">本地试玩版。角色像素素材来自已有素材档案，帝厉魔代理体为原创程序造型。部分新分支使用官方图鉴静态立绘，其他角色保留像素动画。<a href={`${import.meta.env.BASE_URL}THIRD_PARTY_NOTICES.txt`} target="_blank" rel="noreferrer">查看素材来源</a>。</p></Modal>}
  {modal==='abandon'&&<Modal title="结束这段旅途？" onClose={closeModal}><p className="modal-note">当前牌组、金币与进化将结束。已获得的扫描数据和伙伴会保留。</p><div className="modal-actions"><button className="secondary" onClick={closeModal}>继续当前旅途</button><button className="primary" onClick={()=>{send({type:'abandon'});setModal(null);setScreen('home');}}><RotateCcw size={16}/>重新出发</button></div></Modal>}
 </div>;
}
